name: Backporting
author: Thibault Derousseaux <tibdex@gmail.com>
description: Automatically backport PRs to other branches by simply labeling them.
inputs:
  body_template:
    description: >
      Lodash template for the backport PR's body.

      The data properties are:
        - base: backport PR's base branch
        - body: original PR's body
        - mergeCommitSha: SHA of the original PR's merge commit
        - number: original PR's number
    default: "Backport <%= mergeCommitSha %> from #<%= number %>."
  head_template:
    description: >
      Lodash template for the backport PR's head branch.

      The data properties are:
        - base: backport PR's base branch
        - number: original PR's number
    default: "backport-<%= number %>-to-<%= base %>"
  label_pattern:
    description: >
      The regular expression pattern that PR labels will be tested on to decide whether the PR should be backported and where.
      The backport PR's base branch will be extracted from the pattern's required `base` named capturing group.
    default: "^backport (?<base>([^ ]+))$"
  labels_template:
    description: >
      Lodash template compiling to a JSON array of labels to add to the backport PR.

      The data properties are:
        - base: backport PR's base branch
        - labels: array containing the original PR's labels, excluding those matching `label_pattern`.
    default: "[]"
  github_token:
    description: Token for the GitHub API.
    required: true
  title_template:
    description: >
      Lodash template for the backport PR's title.

      The data properties are:
        - base: backport PR's base branch
        - number: original PR's number
        - title: original PR's title
    default: "[Backport <%= base %>] <%= title %>"
outputs:
  created_pull_requests:
    description: An JSON stringified object mapping the base branch of the created pull requests to their number.
runs:
  using: node16
  main: dist/index.js
branding:
  icon: arrow-left-circle
  color: purple
