name: Hotfix Bot
author: Judson Stephenson <jud@jud.me>
description: Automatically backport Hotfix PRs to other branches.
inputs:
  add_labels:
    description: Comma separated list of labels to add to the backport PR.
    required: false
  branches:
    description: Comma separated list of branches to open backport PRs against.
    required: false
    default: develop,staging
  github_token:
    description: Token for the GitHub API.
    required: true
  title_template:
    description: Template for the title of the backport PR.
    required: false
    default: "[Backport {{base}}] {{originalTitle}}"
runs:
  using: node12
  main: dist/index.js
branding:
  icon: arrow-left-circle
  color: purple
