service: backport

provider:
  name: aws
  runtime: nodejs8.10
  stage: production

functions:
  probot:
    handler: src/handler.probot
    events:
      - http: POST /
      - http: GET /probot
    environment:
      APP_ID: ${env:APP_ID}
      DISABLE_STATS: true
      NODE_ENV: production
      PRIVATE_KEY: ${env:PRIVATE_KEY}
      SENTRY_DSN: ${env:SENTRY_DSN}
      WEBHOOK_SECRET: ${env:WEBHOOK_SECRET}
    memorySize: 512

plugins:
  - serverless-webpack
