version: 2.1

jobs:
  check:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn run check-build
      - run: yarn run test --coverage
      - run: yarn run tslint
      - run: yarn run prettier --list-different
      - store_test_results:
          path: reports
      - store_artifacts:
          path: coverage/lcov-report
          destination: coverage

  deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/backport
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: sudo yarn global add now --prefix /usr/local
      - run: now --no-clipboard --token $NOW_TOKEN
      - run: now --token $NOW_TOKEN alias $NOW_ALIAS
      - run: now --token $NOW_TOKEN rm backport --safe --yes

workflows:
  check:
    jobs:
      - check:
          filters:
            branches:
              ignore: master

  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
