version: 2
jobs:
  check:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn run prettier --list-different
      - run: yarn run eslint
      - run: yarn flow check
      - run: yarn run test --coverage
      - store_test_results:
          path: reports
      - store_artifacts:
          path: coverage/lcov-report
          destination: coverage

  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn serverless deploy

workflows:
  version: 2
  check-or-deploy:
    jobs:
      - check:
          filters:
            branches:
              ignore: master
      - deploy:
          filters:
            branches:
              only: master
