version: 2
jobs:
  check:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: yarn run test --coverage
      - run: yarn run tslint
      - run: yarn run prettier --list-different
      - store_test_results:
          path: reports
      - store_artifacts:
          path: coverage/lcov-report
          destination: coverage

  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: sudo yarn global add now --prefix /usr/local
      - run: yarn build
      - run: now --name backport --no-clipboard --token $NOW_TOKEN
      - run: now --token $NOW_TOKEN alias $NOW_ALIAS
      - run: now --token $NOW_TOKEN rm $NOW_ALIAS --safe --yes

workflows:
  version: 2
  check-or-deploy:
    jobs:
      - check:
          filters:
            branches:
              ignore: master
      - deploy:
          filters:
            branches:
              only: master
