version: 2
jobs:
  check:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn run prettier --list-different
      - run: yarn run eslint
      - run: yarn run flow check
      - run: yarn run test --coverage
      - run: yarn run serverless package
      - store_test_results:
          path: reports
      - store_artifacts:
          path: coverage/lcov-report
          destination: coverage
      - store_artifacts:
          path: .serverless
          destination: serverless

  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn run serverless deploy
      - store_artifacts:
          path: .serverless
          destination: serverless

workflows:
  version: 2
  check-or-deploy:
    jobs:
      - check:
          filters:
            branches:
              ignore: master
      - deploy:
          filters:
            branches:
              only: master
