name: Hotfix
on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-18.04
    name: Hotfix
    steps:
      - name: Hotfix
        uses: jud/hotfix@v1
        with:
          branches: develop,staging
          github_token: ${{ secrets.GITHUB_TOKEN }}
